title: Douglas E. Alves
author: Douglas Expedito Alves
email: douglas.expalves@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Site criado com Jekyll.
baseurl: ""
url: "https://dougtq.github.io"
github_username:  dougtq
linkedin_username: dougtq

# Build settings
markdown: kramdown
permalink: /:title
theme: minima
plugins:
  - jekyll-feed
